### PR TITLE
create extensions.json from ha repo

### PR DESCRIPTION
**Pull request by glmnet**
are all of these recommended here too?

### CODE REVIEW

**Comment by Misiu** [comment]
This file is added to gitignore in HA Frontend https://github.com/home-assistant/frontend/blob/dev/.gitignore#L34, we should do the same here.

**Comment by balloob** [comment]
it's added to ignore after the file was created I think. I am not 100% sure the reasoning.

**Comment by glmnet** [comment]
Ohh I created directly in GitHub so maybe an update to .gitignore is required

**Comment by Misiu** [comment]
I think those four are a good strart. We can always add/edit this in the future.

**Pull request merged**
